version: 2
updates:
- package-ecosystem: mix
  directory: "/robotica"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: yaml_elixir
    versions:
    - 2.7.0
  - dependency-name: mint
    versions:
    - 1.2.1
- package-ecosystem: mix
  directory: "/robotica_common"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: yaml_elixir
    versions:
    - 2.6.0
  - dependency-name: tzdata
    versions:
    - 1.1.0
  - dependency-name: dialyxir
    versions:
    - 1.1.0
- package-ecosystem: mix
  directory: "/robotica_ui"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
- package-ecosystem: mix
  directory: "/robotica_nerves"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
