#!/bin/sh
set -e
set -x

cd "$(dirname "$0")"
export MIX_TARGET=host
export MIX_ENV=test

. ./.envrc.test

for i in robotica_common robotica robotica_nerves robotica_docker; do
    (
        echo "----- $i -----"
        cd $i
        mix deps.get
        mix format --check-formatted
        mix credo --strict
        mix compile
        mix test
        mkdir -p priv/plts
        mix dialyzer
    )
done
