#!/bin/sh
set -e
set -x

cd "$(dirname "$0")"
export MIX_ENV=test

for i in robotica_common robotica robotica_face robotica_hello robotica_ui ceryx ceryx_docker; do
    (
        echo "----- $i -----"
        cd $i
        # test -f .envrc && . ./.envrc
        mix deps.get
        mix deps.clean --unlock --unused
        # rm -rf _build
        mix compile
    )
done

for i in robotica_nerves ceryx_nerves; do
    for target in host rpi3; do
        export MIX_TARGET="$target"
        (
            echo "----- $i $target -----"
            cd $i
            # test -f .envrc && . ./.envrc
            mix deps.get
            mix deps.clean --unlock --unused
            # rm -rf _build
            mix compile
        )
    done
done

for i in robotica_face robotica_hello; do
    (
        echo "----- $i -----"
        cd $i
        npm install --prefix assets
        npm run deploy --prefix assets
        mix phx.digest
    )
done
