#!/bin/sh
set -e
set -x

cd "$(dirname "$0")"
export MIX_ENV=test
export BUILD_WITHOUT_QUIC=true

for i in robotica_common robotica robotica_ui; do
    (
        echo ""
        echo "----- $i -----"
        cd $i
        # test -f .envrc && . ./.envrc
        mix deps.get
        mix deps.clean --unlock --unused
        # rm -rf _build
        mix compile
    )
done

for i in robotica_nerves robotica_docker; do
    for target in host rpi3; do
        export MIX_TARGET="$target"
        (
            echo ""
            echo "----- $i $target -----"
            cd $i
            # test -f .envrc && . ./.envrc
            mix deps.get
            mix deps.clean --unlock --unused
            # rm -rf _build
            mix compile
        )
    done
done
