# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build-plugins:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/elixir:1.9

    steps:
      - checkout

      - run:
          name: Install hex and rebar
          command: |
            cd robotica_plugins
            mix local.hex --force
            mix local.rebar --force

      - run:
          name: Install dependencies
          command: |
            cd robotica_plugins
            export MIX_ENV=test
            mix deps.get

      - run:
          name: Compile
          command: |
            cd robotica_plugins
            export MIX_ENV=test
            mix compile

      - run:
          name: Run tests
          command: |
            cd robotica_plugins
            mix test

      - store_test_results:
          path: robotica_plugins/_build/test/lib/robotica_plugins

  build-robotica:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/elixir:1.9

    steps:
      - checkout

      - run:
          name: Install hex and rebar
          command: |
            cd robotica
            mix local.hex --force
            mix local.rebar --force

      - run:
          name: Install dependencies
          command: |
            cd robotica
            export MIX_ENV=test
            mix deps.get

      - run:
          name: Compile
          command: |
            cd robotica
            export MIX_ENV=test
            mix compile

      - run:
          name: Run tests
          command: |
            cd robotica
            export SECRET_KEY_BASE="A+1sbKi4zpi1o5Aac2fY6dkinjhNC6+OO6o0DQC6x/mHUfyVK5jZLbH6oQiRFJN0"
            export GUARDIAN_SECRET="Pbs+1dq8+DH3QMqKX5KgtTVoPgYp+5AQQ8mY56ThEe4fbVblZkWah4gW2NiCTP84"
            export SIGNING_SALT="lFJrL13YHIH/wScmyEG7U2hXsoNqxSJB"
            mix test

      - store_test_results:
          path: robotica/_build/test/lib/robotica

  build-ui:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/elixir:1.9

    steps:
      - checkout

      - run:
          name: Install hex and rebar
          command: |
            cd robotica_ui
            mix local.hex --force
            mix local.rebar --force

      - run:
          name: Install dependencies
          command: |
            cd robotica_ui
            export MIX_ENV=test
            mix deps.get

      - run:
          name: Compile
          command: |
            cd robotica_ui
            export MIX_ENV=test
            mix compile

      - run:
          name: Run tests
          command: |
            cd robotica_ui
            mix test

      - store_test_results:
          path: robotica_ui/_build/test/lib/robotica_ui

  build-face:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/elixir:1.9

    steps:
      - checkout

      - run:
          name: Install hex and rebar
          command: |
            cd robotica_face
            mix local.hex --force
            mix local.rebar --force

      - run:
          name: Install dependencies
          command: |
            cd robotica_face
            export MIX_ENV=test
            mix deps.get

      - run:
          name: Compile
          command: |
            cd robotica_face
            export MIX_ENV=test
            mix compile

      - run:
          name: Run tests
          command: |
            cd robotica_face
            export SECRET_KEY_BASE="A+1sbKi4zpi1o5Aac2fY6dkinjhNC6+OO6o0DQC6x/mHUfyVK5jZLbH6oQiRFJN0"
            export GUARDIAN_SECRET="Pbs+1dq8+DH3QMqKX5KgtTVoPgYp+5AQQ8mY56ThEe4fbVblZkWah4gW2NiCTP84"
            export SIGNING_SALT="lFJrL13YHIH/wScmyEG7U2hXsoNqxSJB"
            mix test

      - store_test_results:
          path: robotica_face/_build/test/lib/robotica_face

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-plugins:
          filters:
            tags:
              only: /.*/
      - build-robotica:
          filters:
            tags:
              only: /.*/
      - build-face:
          filters:
            tags:
              only: /.*/
