# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/elixir:1.8
        environment:
          DATABASE_URL_TEST: postgresql://root@localhost/circle_test?sslmode=disable

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    steps:
      - checkout

      - run:
          name: Install hex and rebar
          command: |
            mix local.hex --force
            mix local.rebar --force

      - run:
          name: Install dependencies
          command: |
            mix deps.get

      - run:
          name: Compile
          command: |
            mix compile

      - run:  # special utility that stalls main process until DB is ready
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Run tests
          command: |
            export SECRET_KEY_BASE="A+1sbKi4zpi1o5Aac2fY6dkinjhNC6+OO6o0DQC6x/mHUfyVK5jZLbH6oQiRFJN0"
            export GUARDIAN_SECRET="Pbs+1dq8+DH3QMqKX5KgtTVoPgYp+5AQQ8mY56ThEe4fbVblZkWah4gW2NiCTP84"
            export SIGNING_SALT="lFJrL13YHIH/wScmyEG7U2hXsoNqxSJB"
            mix test

      - store_test_results:
          path: _build/test/lib/robotica_face

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
