name: Build and Deploy to Docker Hub

on:
  - push
  - pull_request

jobs:
  robotica_common:
    uses: brianmay/workflows/.github/workflows/elixir.yaml@main
    with:
      build_npm_assets: false
      directory: "robotica_common"
      mix_cache_postfix: ""
      plts_cache_postfix: "-3"

  robotica:
    uses: brianmay/workflows/.github/workflows/elixir.yaml@main
    with:
      build_npm_assets: false
      directory: "robotica"
      mix_cache_postfix: ""
      plts_cache_postfix: "-3"

#  robotica_ui:
#    uses: brianmay/workflows/.github/workflows/elixir.yaml@main
#    with:
#      build_npm_assets: false
#      directory: "robotica_ui"
#      mix_cache_postfix: ""
#      plts_cache_postfix: "-2"

  robotica_docker:
    uses: brianmay/workflows/.github/workflows/elixir.yaml@main
    with:
      build_npm_assets: false
      directory: "robotica_docker"
      mix_cache_postfix: ""
      plts_cache_postfix: "-3"

  push:
    name: Push
    uses: brianmay/workflows/.github/workflows/docker.yaml@main
    secrets:
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      DEPLOY_SECRET: ${{ secrets.DEPLOY_SECRET }}
    needs:
      - robotica_common
      - robotica
      - robotica_docker
