name: Build and Deploy to Docker Hub

on:
  - push
  - pull_request

jobs:
  robotica_common:
    uses: brianmay/workflows/.github/workflows/elixir.yaml@b7166456591b3ce36895b52acfa634b4ef33ad5f
    with:
      build_npm_assets: false
      directory: "robotica_common"
      mix_cache_postfix: ""
      plts_cache_postfix: ""

  robotica:
    uses: brianmay/workflows/.github/workflows/elixir.yaml@b7166456591b3ce36895b52acfa634b4ef33ad5f
    with:
      build_npm_assets: false
      directory: "robotica"
      mix_cache_postfix: ""
      plts_cache_postfix: ""

  robotica_ui:
    uses: brianmay/workflows/.github/workflows/elixir.yaml@b7166456591b3ce36895b52acfa634b4ef33ad5f
    with:
      build_npm_assets: false
      directory: "robotica_ui"
      mix_cache_postfix: ""
      plts_cache_postfix: ""

  robotica_face:
    uses: brianmay/workflows/.github/workflows/elixir.yaml@b7166456591b3ce36895b52acfa634b4ef33ad5f
    with:
      build_npm_assets: true
      directory: "robotica_face"
      mix_cache_postfix: ""
      plts_cache_postfix: ""

  robotica_docker:
    uses: brianmay/workflows/.github/workflows/elixir.yaml@b7166456591b3ce36895b52acfa634b4ef33ad5f
    with:
      build_npm_assets: false
      directory: "robotica_docker"
      mix_cache_postfix: ""
      plts_cache_postfix: ""

  push:
    name: Push
    uses: brianmay/workflows/.github/workflows/docker.yaml@b7166456591b3ce36895b52acfa634b4ef33ad5f
    needs:
      - robotica_common
      - robotica
      - robotica_ui
      - robotica_face
      - robotica_docker
