name: Test

on:
  - push
  - pull_request

jobs:
  robotica_common:
    uses: brianmay/workflows/.github/workflows/elixir.yaml@main
    with:
      build_npm_assets: false
      directory: "robotica_common"
      mix_cache_postfix: ""
      plts_cache_postfix: "-3"

  robotica:
    uses: brianmay/workflows/.github/workflows/elixir.yaml@main
    with:
      build_npm_assets: false
      directory: "robotica"
      mix_cache_postfix: ""
      plts_cache_postfix: "-3"

#  robotica_ui:
#    uses: brianmay/workflows/.github/workflows/elixir.yaml@main
#    with:
#      build_npm_assets: false
#      directory: "robotica_ui"
#      mix_cache_postfix: ""
#      plts_cache_postfix: "-2"
